version: '3'
services:
    mysql:
        image: mysql:5
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    phpfpm:
        image: johnpbloch/phpfpm:latest
        depends_on:
            - mysql
        volumes:
            - './:/app'
        working_dir: /app
        restart: always
